name: IAC - Provision Azure Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Create Terraform Variables File
      uses: actions/create-file@v3
      with:
        path: terraform.tfvars
        content: |
          client_id = ${{ secrets.ARM_CLIENT_ID }}
          client_secret = ${{ secrets.ARM_CLIENT_SECRET }}
          subscription_id = ${{ secrets.ARM_SUBSCRIPTION_ID }}
          tenant_id = ${{ secrets.ARM_TENANT_ID }}

    - name: Terraform Init
      working-directory: ./iac/azure
      run: terraform init -var-file=terraform.tfvars

    - name: Terraform Apply
      working-directory: ./iac/azure
      run: terraform apply -var-file=terraform.tfvars -auto-approve